project_id = "cslumjyomkyhqzscspwc"

[functions.fund-chat]
verify_jwt = false

[functions.market-data]
verify_jwt = false

[functions.stock-prices]
verify_jwt = false

[functions.fund-navs]
verify_jwt = false
